### ISSUE TITLE
Installation issue within python 3.6

### ISSUE THREAD

**Issue by zgxlhy** [jawahar273/practNLPTools-lite#1]
Hi, I cannot install correctly within python 3.6 in windows, I use
`python setup.py install` to install and self-test. But I got such mistake like "'Annotator' object has no attribute 'java_clr'" Is there anything more I need to do except installing it?

**Comment by jawahar273** [comment]
I am very Sry to say this one, that I have not tryed in Windows
Wait for till night I will make corrections and I will ping u a mail

On 21-Apr-2017 1:03 AM, "GaoxiangZHOU" <notifications@github.com> wrote:

Hi, I cannot install correctly within python 3.6 in windows, I use
python setup.py install to install and self-test. But I got such mistake
like "'Annotator' object has no attribute 'java_clr'" Is there anything
more I need to do except installing it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jawahar273/practNLPTools-lite/issues/1>, or mute the
thread

**Comment by jawahar273** [comment]
![pntl jar_clr](https://cloud.githubusercontent.com/assets/7668497/25287346/a364cc88-26de-11e7-83bc-24e08a932ff3.png)
there is no problem for me in Window. Pls recheck you's installing steps.
if u still face any problem, pass  me a mail to jawahar273@gmail.com
